# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# ------------------------ TODO ce bloc est à virer ; c'est le dashboard
enable: true
api:
  insecure: true
# ------------------------ ce bloc est à virer ; c'est le dashboard
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

log:
  filePath: "/logs/error.log"

accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100

# # TODO: il  faut gérer ce fichier de config soit via passage d'args à traefik, soit via composition, soit via une surcharge
# #       soit via des templates ansible

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    # TODO: cabler le dashboard avec stack.services.traefik.vars.enable_dashboard
    dashboard:
      rule: Host(`{{ env "TRAEFIK_DASHBOARD_FQDN"}}`) && (PathPrefix(`/api`) || Host(`{{ env "TRAEFIK_DASHBOARD_FQDN"}}`) && PathPrefix(`/dashboard`))
      service: "api@internal"
      # TODO faut remettre ça
      # entryPoints:
      #   - web-secure
      # middlewares:
      #   - auth
      # tls:
      #   certResolver: letsencrypt

    web-secure-colander:
      rule: Host(`{{ env "COLANDER_FQDN"}}`)
      entryPoints:
        - web-secure
      middlewares:
        - compress-http
        - csrf
      service: colander
    #   # TODO faut remettre ça
      tls:
        certResolver: letsencrypt
    web-secure-threatr:
      rule: Host(`{{ env "THREATR_FQDN"}}`)
      entryPoints:
        - web-secure
      middlewares:
        - compress-http
        - csrf
      service: threatr
      # TODO faut remettre ça
      tls:
        certResolver: letsencrypt
    web-secure-cyberchef:
      rule: Host(`{{ env "CYBERCHEF_FQDN"}}`)
      entryPoints:
        - web-secure
      middlewares:
        - compress-http
        - csrf
      service: cyberchef
      # TODO faut remettre ça
      tls:
        certResolver: letsencrypt

  middlewares:
    compress-http:
      # https://doc.traefik.io/traefik/middlewares/http/compress/
      compress: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    # TODO: cabler le dashboard avec stack.services.traefik.vars.enable_dashboard
    # auth:
    #   basicAuth:
    #     users:
    #   {{/*    - "{{ colander_vault.traefik_admin_user }}:{{ colander_vault.traefik_admin_password | ansible.builtin.password_hash('bcrypt', rounds=4, salt=colander_vault.traefik_auth_salt) }}"  */}}

  services:
    colander:
      loadBalancer:
        servers:
          - url: http://colander-front:5000
    threatr:
      loadBalancer:
        servers:
          - url: http://threatr-front:5000
    cyberchef:
      loadBalancer:
        servers:
          - url: http://cyberchef:8000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    # filename: /etc/traefik/traefik.yml
    directory: /etc/traefik/
    watch: true
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/default.crt
        keyFile: /etc/traefik/certs/default.key
