include:
  - "compose-base.yml"
  - "compose-colander.yml"
  - "compose-threatr.yml"

---

# {{ ansible_managed }}

volumes:
  # production_traefik:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "{{ stack.services.traefik.volumes.config }}"
  #     o: bind
  # production_traefik_logs:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "{{ stack.services.traefik.volumes.logs }}"
  #     o: bind
  production_colander_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "{{ stack.services.colander_postgres.volumes.data }}"
      o: bind
  production_colander_postgres_backups:
    driver: local
    driver_opts:
      type: none
      device: "{{ stack.services.colander_postgres.volumes.backups }}"
      o: bind
# {% if flavor.use_threatr %}
  # production_threatr_postgres_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "{{ stack.services.threatr_postgres.volumes.data }}"
  #     o: bind
  # production_threatr_postgres_backups:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "{{ stack.services.threatr_postgres.volumes.backups }}"
  #     o: bind
# {% endif %}
  production_minio_data:
    driver: local
    driver_opts:
      type: none
      device: "{{ stack.services.minio.volumes.data }}"
      o: bind
