- name: Get current user ID
  ansible.builtin.getent:
    database: passwd
    key: '{{ ansible_user }}'
  when: docker_rootless

- name: Cache the DOCKER_HOST variable
  ansible.builtin.set_fact:
    docker_host: 'unix:///run/user/{{ getent_passwd[ansible_user][1] }}/docker.sock'
  when: docker_rootless

- name: Cache the DOCKER_SOCKET_PATH variable
  ansible.builtin.set_fact:
    docker_socket_path: '/run/user/{{ getent_passwd[ansible_user][1] }}/docker.sock'
  when: docker_rootless