- include_tasks: configure.yml
  when: use_docker_compose

- include_tasks: deploy.yml
  when: use_docker_compose

- include_tasks: summarize.yml
  when: use_docker_compose

- include_tasks: teardown.yml
  when: use_docker_compose
