- import_tasks: configure.yml
  when: use_docker_compose

- import_tasks: deploy.yml
  when: use_docker_compose

- import_tasks: summarize.yml
  when: use_docker_compose

- import_tasks: teardown.yml
  when: use_docker_compose
