- name: Update the whole stack
  community.docker.docker_compose_v2_pull:
    project_src: '{{ colander_installation_path }}'
    docker_host: '{{ docker_host }}'

- name: Start the whole stack
  community.docker.docker_compose_v2:
    project_src: '{{ colander_installation_path }}'
    docker_host: '{{ docker_host }}'
    state: present
