---
- name: Deploy Colander
  hosts: colander
  gather_facts: no
  tasks:
    - include_role:
        name: colander
        tasks_from: docker-info
    - include_role:
        name: colander
        tasks_from: backup
    - include_role:
        name: colander
        tasks_from: backups
