---
- name: Configure
  hosts: local
  gather_facts: no
  vars_prompt:
    - name: root_domain
      prompt: Root domain name
      unsafe: false
      private: false

  roles:
    - role: configuration
