---
- name: Teardown Colander
  hosts: colander
  gather_facts: no
  tasks:
    - include_role:
        name: colander
        tasks_from: docker-info
    - include_role:
        name: colander
        tasks_from: teardown
